/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Afonso
 */
public class TelaMenu extends javax.swing.JPanel  {
    JFrame meuFrame;
    /**
     * Creates new form TelaMenu
     */
    public TelaMenu(JFrame frame) {
        initComponents();
        meuFrame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoJogar = new javax.swing.JButton();
        FnomeJogador = new javax.swing.JTextField();
        fecha = new javax.swing.JButton();
        botaoRanking = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 1, 223));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Show_do_milhao-PhotoRoom.png-PhotoRoom.png"))); // NOI18N

        botaoJogar.setBackground(new java.awt.Color(113, 4, 4));
        botaoJogar.setFont(new java.awt.Font("Comic Sans MS", 0, 38)); // NOI18N
        botaoJogar.setForeground(new java.awt.Color(255, 255, 255));
        botaoJogar.setText("Jogar");
        botaoJogar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogarActionPerformed(evt);
            }
        });

        FnomeJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnomeJogadorActionPerformed(evt);
            }
        });

        fecha.setBackground(new java.awt.Color(113, 4, 4));
        fecha.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("X");
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        botaoRanking.setBackground(new java.awt.Color(113, 4, 4));
        botaoRanking.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        botaoRanking.setForeground(new java.awt.Color(255, 255, 255));
        botaoRanking.setText("Ranking");
        botaoRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRankingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(fecha)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoJogar, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(FnomeJogador)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(botaoRanking)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fecha)))
                .addGap(29, 29, 29)
                .addComponent(botaoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(FnomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogarActionPerformed
     
        if (!(FnomeJogador.getText().length() > 2 )|| FnomeJogador.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um nome para comecar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            
        PainelPerguntas painelPerguntas = new PainelPerguntas();
        painelPerguntas.setSize(1000,650);
        painelPerguntas.setLocation(0,0);
        painelPerguntas.setNomeJogador(FnomeJogador.getText());
        Menu.adicionaPanel(painelPerguntas);
        }
    }//GEN-LAST:event_botaoJogarActionPerformed

    private void FnomeJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnomeJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnomeJogadorActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
      meuFrame.dispose();
        
    }//GEN-LAST:event_fechaActionPerformed

    private void botaoRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRankingActionPerformed
        // TODO add your handling code here:
         RankingPanel ranking = new RankingPanel();
        ranking.setSize(1000,650);
        ranking.setLocation(0,0);
        Menu.adicionaPanel(ranking);
    }//GEN-LAST:event_botaoRankingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FnomeJogador;
    private javax.swing.JButton botaoJogar;
    private javax.swing.JButton botaoRanking;
    private javax.swing.JButton fecha;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
